config/routes.rb
Rails.application.routes.draw do
  root to: "contributions#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :contributions, only:%i(destroy show) do
    resources :comments, only: %i(create)
    collection do
      get :top
      get :home
      get :news
    end
  end
  resources :posts, only:%i(new create edit update)
  resources :ques, only: %i(new create destroy)
  resources :votes, only: %i(create)
  resources :profiles, only:%i(show edit update)
  resources :user_relations, only: %i(create destroy) do
    member do
      get :show_following
      get :show_followers
    end
  end
  resources :favorites, only: %i(create destroy) do
    member do
      get :show_favorites
      get :show_favorited_by
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :contribution

  validates :content, length: { maximum: 500 }, presence: true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  has_one :post, dependent: :destroy
  has_one :que, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy

  scope :self_contributions, -> (current_user_id){ where(user_id: current_user_id) }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :contribution
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :que
  has_many :votes, dependent: :destroy
  validates :option_name, length: { maximum: 30 }, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contribution
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :screen_name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 300 }
end

app/models/que.rb
class Que < ApplicationRecord
  belongs_to :contribution
  has_many :options, dependent: :destroy
  validates :question, length: { maximum: 500 }, presence: true
  enum que_type: %i(options)
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :validatable
  validates :user_name, presence: true, length: { maximum: 20 }
  has_one :profile, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :active_relationships, foreign_key: "follower_id", class_name: "UserRelation", dependent: :destroy
  has_many :passive_relationships, foreign_key: "followed_id", class_name: "UserRelation", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :favorite_contributions, through: :favorites, source: :contribution
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def favorited?(contribution)
    favorites.where(contribution_id: contribution.id).exists?
  end
end

app/models/user_relation.rb
class UserRelation < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :option
  belongs_to :user
  validates :option_id, uniqueness: { scope: :user_id }
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def top
  end

  def home
    unless user_signed_in?
      redirect_to top_contributions_path
    else
      @post = Post.new
      @contributions = home_contributions(current_user).order(created_at: :desc)
    end
  end

  def news
  end

  def destroy
    authenticate_user!
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    redirect_to root_path, notice: I18n.t("activerecord.flash.contribution.destroy")
  end

  private
  def home_contributions(current_user)
    ids = current_user.following.ids << current_user.id
    # Contribution.all.includes(:post, [que: :options], [user: [:profile, :favorites, :comments]]).where(user_id: ids)
      Contribution.includes(:post,:favorites,:comments,:user,[que: [options: :votes]]).where(user_id: ids)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
    respond_to do |format|
      format.js { render :new }
    end
  end

  def create
    @user = current_user
    @contribution = @user.contributions.build
    @contributions = home_contributions(current_user).order(created_at: :desc)
    @post = @contribution.build_post(post_params)
    if @post.save
      redirect_to home_contributions_path, notice: I18n.t("activerecord.flash.post.create")
    else
      render home_contributions_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
      flash[:notice] = I18n.t("activerecord.flash.post.edit")
    else
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end

    def home_contributions(current_user)
      ids = current_user.following.ids << current_user.id
      Contribution.includes(:post, [user: [:profile, :favorites]]).where(user_id: ids)
    end
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
  before_action :authenticate_user!
  respond_to? :js, only: %i(new)

  def new
    @que = Que.new
    4.times do
      @que.options.build
    end
  end

  def create
    @user = current_user
    @contribution = @user.contributions.build
    @contributions = home_contributions(current_user).order(created_at: :desc)
    @que = @contribution.build_que(que_params)
    if @que.save
      redirect_to home_contributions_path, notice: I18n.t("activerecord.flash.que.create")
    else
      render :new
    end
  end

  private
    def que_params
      params.require(:que).permit(
        :question,
        :que_type,
        options_attributes: [:id,
                             :option_name,
                             :_destroy]
      )
    end

    def home_contributions(current_user)
      ids = current_user.following.ids << current_user.id
      Contribution.includes(:post, [que: :options], [user: [:profile, :favorites, :comments]]).where(user_id: ids)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def side_menu_display?
    controllers = ["sessions","registrations"]
    actions = ["top"]
    if user_signed_in? && controllers.exclude?(controller.controller_name) && actions.exclude?(controller.action_name) 
      true
    else
      false
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ques_helper.rb
module QuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_fixed_footer
    "fixed" if controller.controller_name == "registrations" || controller.controller_name == "sessions"
  end

  def not_to_scroll
    "not_scroll" if controller.controller_name == "registrations" || controller.controller_name == "sessions"
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def already_voted?(contribution)
    return false unless user_signed_in?
      votes = Vote.where(user_id: current_user.id)
      votes.where(option_id: contribution.que.options.ids).present?
  end
end

app/views/contributions/_error.html.slim
- if instance.errors.any?
  #error_explanation
    ul
      - instance.errors.full_messages.each do |message|
        li
          = message

app/views/contributions/_index.html.slim
- unless contribution.post.nil?
  .post
    p.post_user_name
      = I18n.t("activerecord.attributes.profile.screen_name")
      = link_to "#{contribution.user.profile.screen_name}" , profile_path(contribution.user.profile.id)
    p.post_content
      = contribution.post.content
    p.post_info
      = I18n.t("activerecord.views.created_at")
      = contribution.created_at.strftime('%Y/%m/%d %H:%M')
    .comments
      div class="show_comments_#{contribution.id}"
        p.comment_starts
          = I18n.t("activerecord.models.comments")
        ul
          - contribution.comments.each do |comment|
              li.each_comment
                p.comment_user_name
                  = link_to "#{comment.user.profile.screen_name}", profile_path(comment.user.profile.id)
                p.comment_content
                  = comment.content
                p.comment_date
                  = comment.created_at.strftime('%Y/%m/%d %H:%M')
      - if user_signed_in?
        div id="comment_form"
          = render partial: 'comments/form', locals: { comment: contribution.comments.build, contribution: contribution }
    ul.post_menu
      li
        - if user_signed_in?
          div id="favorites_button_#{contribution.id}"
            - unless current_user.favorited?(contribution)
              = form_with(model: current_user.favorites.build(contribution_id: contribution.id)) do |f|
                = f.hidden_field :contribution_id, id: "contribution_id_#{contribution.id}"
                = f.submit
            - else
              = form_with(model: current_user.favorites.find_by(contribution_id: contribution.id), method: :delete ) do |f|
                = f.submit
            #favorites_count
              - if contribution.favorite_users.exists?
                = link_to(show_favorited_by_favorite_path(contribution.id)) do
                  = contribution.favorite_users.size
                  = I18n.t("activerecord.views.user_liked")
              - else
                = contribution.favorite_users.size
                = I18n.t("activerecord.views.user_liked")
      - if user_signed_in? && current_user.id == contribution.user.id
        li
          = link_to I18n.t("activerecord.views.edit"), edit_post_path(contribution.post.id), class:"edit_link"
    .comments_open
      div id="comments_count_#{contribution.id}"
        p
          | コメント：
          = contribution.comments.count
          | 件
          span#open_message
            | ▼コメントを表示
- else
  .que
    p.post_user_name
      = I18n.t("activerecord.attributes.profile.screen_name")
      = link_to "#{contribution.user.profile.screen_name}" , profile_path(contribution.user.profile.id)
    p.post_content
      | Q.
      = contribution.que.question
    .que_options
      - unless already_voted?(contribution)
        div id="que_options_#{contribution.id}"
          - contribution.que.options.each do |option|
            = link_to votes_path(contribution_id: contribution.id, option_id: option.id), method: :post, remote: true do
              p
                | #{option.option_name}
      - else
        - ranks = contribution.que.options.sort {|a,b| b.votes.count <=> a.votes.count}
        .result
          h3
            | 投票結果
          table
            - ranks.each_with_index do |rank,i|
              tr
                th
                  span.rank_number
                    = i + 1
                  span.rank_option_name
                    = rank.option_name
                  - if user_signed_in? && current_user.votes.find_by(option_id: rank.id).present?
                    span.voted_mark
                      | ★
                td
                  span.rank_votes_count
                    = rank.votes.size
                    |票
    p.post_info
      = I18n.t("activerecord.views.created_at")
      = contribution.created_at.strftime('%Y/%m/%d %H:%M')
    .comments
      div class="show_comments_#{contribution.id}"
        p.comment_starts
          = I18n.t("activerecord.models.comments")
        ul
          - contribution.comments.each do |comment|
              li.each_comment
                p.comment_user_name
                  = link_to "#{comment.user.profile.screen_name}", profile_path(comment.user.profile.id)
                p.comment_content
                  = comment.content
                p.comment_date
                  = comment.created_at.strftime('%Y/%m/%d %H:%M')
      - if user_signed_in?
        div id="comment_form"
          = render partial: 'comments/form', locals: { comment: contribution.comments.build, contribution: contribution }
    ul.post_menu
      li
        - if user_signed_in?
          div id="favorites_button_#{contribution.id}"
            - unless current_user.favorited?(contribution)
              = form_with(model: current_user.favorites.build(contribution_id: contribution.id)) do |f|
                = f.hidden_field :contribution_id, id: "contribution_id_#{contribution.id}"
                = f.submit
            - else
              = form_with(model: current_user.favorites.find_by(contribution_id: contribution.id), method: :delete ) do |f|
                = f.submit
            #favorites_count
              - if contribution.favorite_users.exists?
                = link_to(show_favorited_by_favorite_path(contribution.id)) do
                  = contribution.favorite_users.size
                  = I18n.t("activerecord.views.user_liked")
              - else
                = contribution.favorite_users.size
                = I18n.t("activerecord.views.user_liked")
        - if user_signed_in? && current_user.id == contribution.user.id
          li
            = link_to I18n.t("activerecord.views.destroy"), contribution_path(contribution.id), method: :delete, data: { confirm: "queを削除しますか？"},class:"delete_link"
    .comments_open
      div id="comments_count_#{contribution.id}"
        p
          | コメント：
          = contribution.comments.count
          | 件
          span#open_message
            | ▼コメントを表示

app/views/contributions/home.html.slim
.wrapper.clearfix
  #contribution_form.clearfix
    = render partial: "posts/form", locals: { post: @post }
  #timeline
    = render partial: "contributions/index", collection: @contributions, as: :contribution

app/views/contributions/news.html.slim
.wrapper.clearfix
  - unless user_signed_in?
    .back_button_place
      .back_button
        = link_to I18n.t("activerecord.views.top"), top_contributions_path
  #timeline
    #result_title
      h2
        = @title
    = render partial: "contributions/index", collection: @searched_contributions, as: :contribution

app/views/contributions/top.html.erb
あああ

app/views/contributions/top.html.slim
.wrapper
  .introduction
    h1#top_copy
      | 人を知り、自分を知る。
    = link_to "neuronって？","#", class:"button", id:"introduction_button"
  .links.clearfix
    .top_login
      img.top_links_pic src="/assets/top_login_pic.png"
      h3
        | アカウントをお持ちの方はこちらからログイン
      = link_to "ログイン", new_user_session_path, class:"button", id:"top_login_button"
      p
        | アカウントを作成していない方は
        = link_to "サインアップ", new_user_registration_path
    .top_news
      img.top_links_pic src="/assets/top_news_pic.png"
      h3
        | まずは最新の話題を見てみましょう。
      = link_to "新着投稿を見る", news_contributions_path, class:"button", id:"top_login_button"
      p
        | 閲覧、queの投票が可能です。