config/routes.rb
Rails.application.routes.draw do
  root to: "contributions#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :contributions, only:%i(destroy show) do
    resources :comments, only: %i(create)
    collection do
      get :top
      get :home
      get :news
    end
  end
  resources :posts, only:%i(new create edit update)
  resources :ques, only: %i(new create destroy)
  resources :votes, only: %i(create)
  resources :profiles, only:%i(show edit update)
  resources :user_relations, only: %i(create destroy) do
    member do
      get :show_following
      get :show_followers
    end
  end
  resources :favorites, only: %i(create destroy) do
    member do
      get :show_favorites
      get :show_favorited_by
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :contribution

  validates :content, length: { maximum: 500 }, presence: true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  has_one :post, dependent: :destroy
  has_one :que, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy

  scope :self_contributions, -> (current_user_id){ where(user_id: current_user_id) }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :contribution
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :que
  has_many :votes, dependent: :destroy
  validates :option_name, length: { maximum: 30 }, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contribution
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :screen_name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 300 }
end

app/models/que.rb
class Que < ApplicationRecord
  belongs_to :contribution
  has_many :options, dependent: :destroy
  validates :question, length: { maximum: 500 }, presence: true
  enum que_type: %i(options)
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :validatable
  validates :user_name, presence: true, length: { maximum: 20 }
  has_one :profile, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :active_relationships, foreign_key: "follower_id", class_name: "UserRelation", dependent: :destroy
  has_many :passive_relationships, foreign_key: "followed_id", class_name: "UserRelation", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :favorite_contributions, through: :favorites, source: :contribution
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def favorited?(contribution)
    favorites.where(contribution_id: contribution.id).exists?
  end
end

app/models/user_relation.rb
class UserRelation < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :option
  belongs_to :user
  validates :option_id, uniqueness: { scope: :user_id }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
    respond_to do |format|
      format.js { render :new }
    end
  end

  def create
    @user = current_user
    @contribution = @user.contributions.build
    @contributions = home_contributions(current_user).order(created_at: :desc)
    @post = @contribution.build_post(post_params)
    if @post.save
      redirect_to home_contributions_path, notice: I18n.t("activerecord.flash.post.create")
    else
      render home_contributions_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
      flash[:notice] = I18n.t("activerecord.flash.post.edit")
    else
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end

    def home_contributions(current_user)
      ids = current_user.following.ids << current_user.id
      Contribution.includes(:post, [user: [:profile, :favorites]]).where(user_id: ids)
    end
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
  before_action :authenticate_user!
  respond_to? :js, only: %i(new)

  def new
    @que = Que.new
    4.times do
      @que.options.build
    end
  end

  def create
    @user = current_user
    @contribution = @user.contributions.build
    @contributions = home_contributions(current_user).order(created_at: :desc)
    @que = @contribution.build_que(que_params)
    if @que.save
      redirect_to home_contributions_path, notice: I18n.t("activerecord.flash.que.create")
    else
      render :new
    end
  end

  private
    def que_params
      params.require(:que).permit(
        :question,
        :que_type,
        options_attributes: [:id,
                             :option_name,
                             :_destroy]
      )
    end

    def home_contributions(current_user)
      ids = current_user.following.ids << current_user.id
      Contribution.includes(:post, [que: :options], [user: [:profile, :favorites, :comments]]).where(user_id: ids)
    end
end

app/controllers/user_relations_controller.rb
class UserRelationsController < ApplicationController
  before_action :authenticate_user!
  respond_to? :js, only: %i(create destroy)

  def show_following
    @user = User.find(params[:id])
  end

  def show_followers
    @user = User.find(params[:id])
  end

  def create
    @user = User.find(params[:user_relation][:followed_id])
    current_user.follow!(@user)
  end

  def destroy
    @user = UserRelation.find(params[:id]).followed
    current_user.unfollow!(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def side_menu_display?
    controllers = ["sessions","registrations"]
    actions = ["top"]
    if user_signed_in? && controllers.exclude?(controller.controller_name) && actions.exclude?(controller.action_name) 
      true
    else
      false
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ques_helper.rb
module QuesHelper
end

app/helpers/user_relations_helper.rb
module UserRelationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_fixed_footer
    "fixed" if controller.controller_name == "registrations" || controller.controller_name == "sessions"
  end

  def not_to_scroll
    "not_scroll" if controller.controller_name == "registrations" || controller.controller_name == "sessions"
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def already_voted?(contribution)
    return false unless user_signed_in?
      votes = Vote.where(user_id: current_user.id)
      votes.where(option_id: contribution.que.options.ids).present?
  end
end

app/views/user_relations/_follow_button.html.slim
div id="follow_button_#{user.id}"
  - unless current_user.following?(user)
    = form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f|
      = f.hidden_field :followed_id
      = f.submit "フォロー"
  - else
    = form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f|
      = f.submit "フォロー解除"

app/views/user_relations/_followed_count.html.slim
- if user.followers.exists?
  span#followed_count
    = link_to "#{user.followers.count}", show_followers_user_relation_path(user.id)
- else
  span#followed_count
    | #{user.followers.count}

app/views/user_relations/_following_count.html.slim
- if user.following.exists?
  span#following_count
    = link_to "#{user.following.count}", show_following_user_relation_path(user.id)
- else
  span#following_count
    | #{user.following.count}

app/views/user_relations/create.js.erb
$("#follow_button_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'user_relations/follow_button', locals: { user: @user } ) %>")
$("#following_count").html("<%= escape_javascript(render partial: 'user_relations/following_count', locals: { user: @user } ) %>")
$("#followed_count").html("<%= escape_javascript(render partial: 'user_relations/followed_count', locals: { user: @user } ) %>")

app/views/user_relations/destroy.js.erb
$("#follow_button_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'user_relations/follow_button', locals: { user: @user } ) %>")
$("#following_count").html("<%= escape_javascript(render partial: 'user_relations/following_count', locals: { user: @user } ) %>")
$("#followed_count").html("<%= escape_javascript(render partial: 'user_relations/followed_count', locals: { user: @user } ) %>")

app/views/user_relations/show_followers.html.slim
.wrapper.clearfix
  h2
    |フォローされているユーザー
  - @user.followers.each do |follower|
    .user_list
      p.user_name
        = link_to "#{follower.profile.screen_name}", profile_path(follower.profile.id)
      p.user_introduction
        = follower.profile.introduction

app/views/user_relations/show_following.html.slim
.wrapper.clearfix
  h2
    |フォローしているユーザー
  - @user.following.each do |following|
    .user_list
      p.user_name
        = link_to "#{following.profile.screen_name}", profile_path(following.profile.id)
      p.user_introduction
        = following.profile.introduction