config/routes.rb
Rails.application.routes.draw do
  root to: "contributions#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :contributions, only:%i(destroy show) do
    resources :comments, only: %i(create)
    collection do
      get :top
      get :home
      get :news
    end
  end
  resources :posts, only:%i(new create edit update)
  resources :ques, only: %i(new create destroy)
  resources :votes, only: %i(create)
  resources :profiles, only:%i(show edit update)
  resources :user_relations, only: %i(create destroy) do
    member do
      get :show_following
      get :show_followers
    end
  end
  resources :favorites, only: %i(create destroy) do
    member do
      get :show_favorites
      get :show_favorited_by
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :contribution

  validates :content, length: { maximum: 500 }, presence: true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  has_one :post, dependent: :destroy
  has_one :que, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy

  scope :self_contributions, -> (current_user_id){ where(user_id: current_user_id) }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :contribution
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :que
  has_many :votes, dependent: :destroy
  validates :option_name, length: { maximum: 30 }, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contribution
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :screen_name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 300 }
end

app/models/que.rb
class Que < ApplicationRecord
  belongs_to :contribution
  has_many :options, dependent: :destroy
  validates :question, length: { maximum: 500 }, presence: true
  enum que_type: %i(options)
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :validatable
  validates :user_name, presence: true, length: { maximum: 20 }
  has_one :profile, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :active_relationships, foreign_key: "follower_id", class_name: "UserRelation", dependent: :destroy
  has_many :passive_relationships, foreign_key: "followed_id", class_name: "UserRelation", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :favorite_contributions, through: :favorites, source: :contribution
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def favorited?(contribution)
    favorites.where(contribution_id: contribution.id).exists?
  end
end

app/models/user_relation.rb
class UserRelation < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :option
  belongs_to :user
  validates :option_id, uniqueness: { scope: :user_id }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
    respond_to do |format|
      format.js { render :new }
    end
  end

  def create
    @user = current_user
    @contribution = @user.contributions.build
    @contributions = home_contributions(current_user).order(created_at: :desc)
    @post = @contribution.build_post(post_params)
    if @post.save
      redirect_to home_contributions_path, notice: I18n.t("activerecord.flash.post.create")
    else
      render home_contributions_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
      flash[:notice] = I18n.t("activerecord.flash.post.edit")
    else
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end

    def home_contributions(current_user)
      ids = current_user.following.ids << current_user.id
      Contribution.includes(:post, [user: [:profile, :favorites]]).where(user_id: ids)
    end
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
  before_action :authenticate_user!
  respond_to? :js, only: %i(new)

  def new
    @que = Que.new
    4.times do
      @que.options.build
    end
  end

  def create
    @user = current_user
    @contribution = @user.contributions.build
    @contributions = home_contributions(current_user).order(created_at: :desc)
    @que = @contribution.build_que(que_params)
    if @que.save
      redirect_to home_contributions_path, notice: I18n.t("activerecord.flash.que.create")
    else
      render :new
    end
  end

  private
    def que_params
      params.require(:que).permit(
        :question,
        :que_type,
        options_attributes: [:id,
                             :option_name,
                             :_destroy]
      )
    end

    def home_contributions(current_user)
      ids = current_user.following.ids << current_user.id
      Contribution.includes(:post, [que: :options], [user: [:profile, :favorites, :comments]]).where(user_id: ids)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  respond_to? :js

  def create
    @contribution = Contribution.find(params[:contribution_id])
    current_user.votes.create(option_id: params[:option_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def side_menu_display?
    controllers = ["sessions","registrations"]
    actions = ["top"]
    if user_signed_in? && controllers.exclude?(controller.controller_name) && actions.exclude?(controller.action_name) 
      true
    else
      false
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ques_helper.rb
module QuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_fixed_footer
    "fixed" if controller.controller_name == "registrations" || controller.controller_name == "sessions"
  end

  def not_to_scroll
    "not_scroll" if controller.controller_name == "registrations" || controller.controller_name == "sessions"
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def already_voted?(contribution)
    return false unless user_signed_in?
      votes = Vote.where(user_id: current_user.id)
      votes.where(option_id: contribution.que.options.ids).present?
  end
end

app/views/posts/_error.html.slim
- if post.errors.any?
  .error_message.alert
    ul
      = post.errors.full_messages.each do |message|
        li
          = message

app/views/posts/_form.html.slim
- if post.errors.any?
  #error_explanation
    ul
      - post.errors.full_messages.each do |message|
        li
          = message
= form_with(model:post, local: true, url:posts_path, class:"clearfix") do |f|
  = f.text_area :content, placeholder: I18n.t("activerecord.views.post_placeholder")
  p.contribution_button
    = f.submit "送信"
p.form_change
  = link_to "que作成フォームに切り替え", new_que_path, remote: true

app/views/posts/create.js.erb
$("#timeline").html("<%= j(render 'contributions/index', { contributions: @user.contributions }) %>");
$("textarea").val("");

app/views/posts/edit.html.slim
.wrapper
  .back_button_place
    = link_to home_contributions_path do
      p.back_button
        | 戻る
  #edit_form
    h2
      | post編集
    = form_with(model:@post,local:true) do |f|
      - if @post.errors.any?
        #error_explanation
          - @post.errors.full_messages.each do |message|
            li
              = message
      = f.text_area :content
      .submit_button.forms
        = f.submit "送信"
    p.delete_link
      = link_to "投稿を削除", contribution_path(@post.contribution.id), method: :delete, data:{ confirm: "本当に削除しますか？" }

app/views/posts/index.js.erb
$("#timeline").html("<%= j(render 'contributions/index', { contributions: @contributions }) %>");
$("textarea").val("");

app/views/posts/new.js.erb
$("#contribution_form").html("<%= j(render 'posts/form', { post: @post }) %>");

app/views/ques/_form.html.slim
= form_with(model: @que, local: true, class:"clearfix") do |f|
  - if @que.errors.any?
    #error_explanation
      ul
        - @que.errors.full_messages.each do |message|
          li
            = message
  = f.label :question
  = f.text_area :question, placeholder: I18n.t("activerecord.views.que_placeholder"), id: "que_form"
  .que_type
    = f.label :que_type
    = f.select :que_type, Que.que_types.keys.map {|k| [I18n.t("activerecord.enums.que.que_type.#{k}"), k]}
  .options_field
    span
      = I18n.t("activerecord.attributes.options.option_name")
      | (質問に対しユーザーが選択し回答します)
    .options
      = f.fields_for :options do |o|
        = o.text_field :option_name, placeholder: I18n.t("activerecord.attributes.options.option_name")
  p.que_submit_button
    = f.submit
p.form_change
  = link_to "post作成フォームに切り替え", new_post_path, remote: true

app/views/ques/create.js.erb
$("#timeline").html("<%= j(render 'contributions/index', { contributions: @contributions }) %>");
$("textarea").val("");
$(".options_field").children("input").val("");

app/views/ques/new.html.slim
.wrapper.clearfix
  #contribution_form
    = render partial: "ques/form", locals: { post: @post }
  #timeline
    = render partial: "contributions/index", collection: @contributions, as: :contribution

app/views/ques/new.js.erb
$("#contribution_form").html("<%= j(render 'ques/form', { que: @que }) %>");

app/views/votes/_result.html.slim
- ranks = contribution.que.options.sort {|a,b| b.votes.count <=> a.votes.count}
.result
  h3
    | 投票結果
  table
    - ranks.each_with_index do |rank,i|
      tr
        th
          span.rank_number
            = i + 1
          span.rank_option_name
            = rank.option_name
          - if user_signed_in? && current_user.votes.find_by(option_id: rank.id).present?
            span.voted_mark
              | ★
        td
          span.rank_votes_count
            = rank.votes.count
            |票

app/views/votes/create.js.erb
$("#que_options_"+"<%= @contribution.id %>").html("<%= escape_javascript(render partial: 'votes/result', locals: { contribution: @contribution } ) %>")