config/routes.rb
Rails.application.routes.draw do
  root to: "contributions#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :contributions, only:%i(destroy show) do
    resources :comments, only: %i(create)
    collection do
      get :top
      get :home
      get :news
    end
  end
  resources :posts, only:%i(new create edit update)
  resources :ques, only: %i(new create destroy)
  resources :votes, only: %i(create)
  resources :profiles, only:%i(show edit update)
  resources :user_relations, only: %i(create destroy) do
    member do
      get :show_following
      get :show_followers
    end
  end
  resources :favorites, only: %i(create destroy) do
    member do
      get :show_favorites
      get :show_favorited_by
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :contribution

  validates :content, length: { maximum: 500 }, presence: true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  has_one :post, dependent: :destroy
  has_one :que, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy

  scope :self_contributions, -> (current_user_id){ where(user_id: current_user_id) }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :contribution
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :que
  has_many :votes, dependent: :destroy
  validates :option_name, length: { maximum: 30 }, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contribution
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :screen_name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 300 }
end

app/models/que.rb
class Que < ApplicationRecord
  belongs_to :contribution
  has_many :options, dependent: :destroy
  validates :question, length: { maximum: 500 }, presence: true
  enum que_type: %i(options)
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :validatable
  validates :user_name, presence: true, length: { maximum: 20 }
  has_one :profile, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :active_relationships, foreign_key: "follower_id", class_name: "UserRelation", dependent: :destroy
  has_many :passive_relationships, foreign_key: "followed_id", class_name: "UserRelation", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :favorite_contributions, through: :favorites, source: :contribution
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def favorited?(contribution)
    favorites.where(contribution_id: contribution.id).exists?
  end
end

app/models/user_relation.rb
class UserRelation < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :option
  belongs_to :user
  validates :option_id, uniqueness: { scope: :user_id }
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
  before_action :authenticate_user!
  respond_to? :js, only: %i(new)

  def new
    @que = Que.new
    4.times do
      @que.options.build
    end
  end

  def create
    @user = current_user
    @contribution = @user.contributions.build
    @contributions = home_contributions(current_user).order(created_at: :desc)
    @que = @contribution.build_que(que_params)
    if @que.save
      redirect_to home_contributions_path, notice: I18n.t("activerecord.flash.que.create")
    else
      render :new
    end
  end

  private
    def que_params
      params.require(:que).permit(
        :question,
        :que_type,
        options_attributes: [:id,
                             :option_name,
                             :_destroy]
      )
    end

    def home_contributions(current_user)
      ids = current_user.following.ids << current_user.id
      Contribution.includes(:post, [que: :options], [user: [:profile, :favorites, :comments]]).where(user_id: ids)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def side_menu_display?
    controllers = ["sessions","registrations"]
    actions = ["top"]
    if user_signed_in? && controllers.exclude?(controller.controller_name) && actions.exclude?(controller.action_name) 
      true
    else
      false
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ques_helper.rb
module QuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_fixed_footer
    "fixed" if controller.controller_name == "registrations" || controller.controller_name == "sessions"
  end

  def not_to_scroll
    "not_scroll" if controller.controller_name == "registrations" || controller.controller_name == "sessions"
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def already_voted?(contribution)
    return false unless user_signed_in?
      votes = Vote.where(user_id: current_user.id)
      votes.where(option_id: contribution.que.options.ids).present?
  end
end

app/views/layouts/application.html.slim
doctype html
html class="#{not_to_scroll}"
  head
    title
      | Neuron
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body.can_scroll_when_height_is_short class="#{not_to_scroll}"
    header.clearfix.none
      p#header_logo
        | neuron
      ul.header_menu
        - if user_signed_in?
          li
            = link_to I18n.t("activerecord.views.home"), root_path
        - unless controller.action_name == "top" || controller.controller_name == "sessions" || controller.controller_name == "registrations"
          li
            = link_to I18n.t("activerecord.views.news"), news_contributions_path
      #header_search_form
        = search_form_for @search, url: news_contributions_path do |f|
          = f.text_field :post_content_or_que_question_cont, placeholder: "検索するテキストを入力"
          = f.submit
    .notifications
      - flash.each do |key, value|
        = content_tag(:div, value, class: key)
    - if side_menu_display?
      .side_menu
        p#now_login
          | ログイン中
        p#current_user_screen_name
          = current_user.profile.screen_name
        ul#side_menu_menu
          li
            = link_to I18n.t("activerecord.views.profile") , profile_path(current_user.profile.id)
          li
            = link_to I18n.t("activerecord.views.favorites"), show_favorites_favorite_path(current_user.id)
        .button.logout_button
          = link_to I18n.t("activerecord.views.log_out"), destroy_user_session_path, method: :delete
    = yield
    footer.none class="#{is_fixed_footer}"
      p#footer_print
        | 2020 Haruka Tezuka